name: bluesky-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - pytest
  - pytest-cov
  - pyomo
  - sympy
  - matplotlib
  - networkx
  - pip
  - pip:
      - mypy
      - ruff
