name: bsky
channels:
  - conda-forge
  - base
  - bioconda
dependencies:
  - python=3.12.5
  - numpy=2.1.1
  - pandas=2.2.2
  - pyomo=6.8.0
  - highs=1.7.2
  - ipopt=3.11.1  # why is this pinned?
  - ruff=0.6.2
  - grequests=0.6.0
  - matplotlib=3.9.2
  - plotly=5.24.0
  - pytest=8.3.2
  - sqlalchemy=2.0.33
  - networkx=3.3
  - openpyxl=3.1.5
  - dash=2.17.1
  - pathlib=1.0.1
  - sympy=1.12.1 # pinning this because version 1.13 seems to have problem with the lambdify operation is res mod
  - toml=0.10.2
  - dash-bootstrap-components=1.6.0
  - tomli=2.0.1
  - tomlkit=0.13.2

# For data_pipeline sample
  - snakemake=8.18.2
  - aiohttp=3.10.5
  - graphviz=11.0.0
  - r-base=4.1.3
  - r-tidyverse=2.0.0
  - r-data.table=1.15.4
  - r-sf=1.0_7
  - r-tigris=2.0.3
  - r-here=1.0.1
  - r-tidycensus=1.4.1
  - r-readxl=1.4.3

# needed?  ... for removal?
  - pylint=3.2.7
  - tabulate=0.9.0


# additional outside conda:  highspy from PyPi (not in conda-verse)
#   So, after making the bsky environment and activating it, run:
#   > pip install highspy