# RUN CONFIGURATION TEMPLATE
# This template provides default placeholders for model configurations.
# Copy or edit this file to create a working run_config.toml.

###################################################################################################
# Universal Inputs

# Default solve mode
default_mode = "gs-combo"  # choices: ["unified-combo", "gs-combo", "standalone"]

# Modules to run
electricity = true
hydrogen = true
residential = true

# Combination solve options
force_10 = false
tol = 0.05
max_iter = 12

# Temporal resolution (inter-annual)
sw_temporal = "default"  # choices: "default", "d8h12", "d4h24", or custom

# Temporal resolution (annual)
start_year = 2023
years = [2025, 2030]

# Spatial resolution
regions = [1]  # replace with valid region IDs


###################################################################################################
# Electricity Inputs

# Switches (0 = off, 1 = on unless noted)
sw_trade = 1
sw_expansion = 1
sw_rm = 1
sw_ramp = 0
sw_reserves = 1

# Aggregate years
sw_agg_years = 1

# Learning
sw_learning = 0


###################################################################################################
# Carbon Policy Inputs

# Legacy root-level carbon cap (short tons, converted internally)
# carbon_cap = 0

# Define one or more carbon cap groups
[[carbon_cap_groups]]
name = "default"
cap = "none"  # "none" disables cap; set numeric value to enable
regions = [1]  # replace with region IDs
allowance_procurement = { "2025" = 0.0, "2030" = 0.0 }
start_bank = 0.0
bank_enabled = true
allow_borrowing = false

# Example of nested table format (alternative style)
[carbon_cap_groups.national]
description = "Default national carbon cap group"


###################################################################################################
# Residential Inputs

scale_load = "enduse"
view_regions = [1]
view_years = [2025]

# Sensitivity
sensitivity = false
change_var = "price"
percent_change = 0
complex = false


###################################################################################################
# Hydrogen Inputs

h2_data_folder = "input/hydrogen/all_regions"
