name: CI

on:
  push:
    branches:
      - main
      - work
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          use-mamba: true
          auto-update-conda: false
          auto-activate-base: false
          activate-environment: bsky
          environment-file: envs/conda_env.yml

      - name: Install additional pip dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        shell: bash -l {0}
        run: pytest
