name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy ruff pytest

      - name: ruff lint
        run: ruff check .

      - name: mypy
        run: mypy --config-file pyproject.toml

      - name: pytest
        env:
          PYTHONWARNINGS: error
        run: pytest
