name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      PIP_CACHE_DIR: ${{ github.workspace }}/.pip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare cache directories
        run: |
          mkdir -p .pip
          mkdir -p .pytest_cache

      - name: Restore pip and pytest caches
        uses: actions/cache@v4
        with:
          path: |
            .pip
            .pytest_cache
          key: ${{ runner.os }}-py311-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-py311-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy ruff pytest pytest-cov

      - name: ruff lint
        run: ruff check .

      - name: mypy
        run: mypy --config-file pyproject.toml

      - name: pytest
        env:
          PYTHONWARNINGS: error
        run: pytest -q --cov=engine --cov=dispatch --cov=policy --cov-report=term-missing --cov-fail-under=80
