name: Tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bsky
          environment-file: envs/conda_env.yml
          auto-update-conda: false
          use-mamba: false

      - name: Show Conda info
        run: |
          conda info
          conda list

      - name: Run unit tests
        run: pytest unit_tests
