name: Tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests (Python 3.12)
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          environment-file: environment.yml
          activate-environment: bluesky-env

      - name: Cache Conda packages
        uses: actions/cache@v4
        with:
          path: ~/.conda/pkgs
          key: ${{ runner.os }}-conda-3.12-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Show Conda diagnostics
        run: |
          conda info
          conda list
          python --version

      - name: Run unit tests
        run: pytest -q --junitxml=pytest.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-3.12
          path: pytest.xml
