name: CI

on:
  push:
    branches:
      - main
      - work
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: bsky
          environment-file: envs/conda_env.yml

      - name: Run pytest
        shell: bash -l {0}
        run: pytest
