name: Tests

on:
  push:
  pull_request:

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          auto-update-conda: false
          activate-environment: bsky
          environment-file: envs/conda_env.yml
          use-mamba: true

      - name: Show conda info
        run: conda info

      - name: Run tests
        run: pytest unit_tests
